name: Code Analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  analyze:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ruff (Linting)
        run: |
          pip install ruff
          ruff check .

      - name: Run Secret Scanning
        uses: yelp/detect-secrets@v1
        with:
          action: scan
